### ISSUE TITLE
faviconの修正

### ISSUE THREAD

**Issue by ikepe** [ichipiro/ichipiro.net#1]
faviconがVercelのアイコンになっているため修正したい

**Comment by ikepe** [comment]
@niyu07 

#4 で修正できていない
ローカル環境で実行すると正しく修正されているが、デプロイ後だと表示されない。

![image](https://github.com/user-attachments/assets/e259cb8d-c8ce-4a2c-8f4c-ebb2fbdd1cd9)

**Comment by niyu07** [comment]
キャッシュの問題でした
